apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: backend-api-production
  namespace: argocd
  labels:
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/environment: production

spec:
  project: default

  source:
    repoURL: https://github.com/abhishekyashpal/api-gitops.git
    targetRevision: master
    path: apps/backend-api/chart
    helm:
      releaseName: backend-api-production
      valueFiles:
        - values.yaml
        - values-production.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: backend-api-production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - Validate=true
      - ServerSideApply=true

    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: backend-api
        app.kubernetes.io/environment: production
