apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-api-production

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - replicas-patch.yaml

images:
  - name: developerkingabhi/api-project
    newTag: latest